setup.sh

Issue#2|fix tex

---

appstore.sh

:new: Add new app install command

---

app.sh

:wrench: Change eclipse version

---

settings/iTerm2/com.googlecode.iterm2.plist

:wrench: Update iTerm plist

---

app.sh

:sparkles: Delete onyx install code

---

README.md

:sparkles: Update README file

---

appstore.sh

:sparkles: Delete App Store app

---

app.sh

Add install code for `imageoptim`.

:new: Add GUI App

---

setup.sh

modify: the way to take latest TeX version

---

setup.sh

I modified node block.
details: _v7.0.0_(specific version) -> _latest_(nodebrew option)
such as...
`nodebrew install-binary latest`
`nodebrew use latest`

modify: the way to take latest node version

---

settings/zsh/private.zsh

I appended latex compile function(_texc_) which works on zsh.
please check :star2:

append: latex compile function in setting/zsh/private.zsh

---

setup.sh

setup.sh have come to be able to memorize user password and execute sudo command with it.

modify: improved sudo timeout in setup.sh

---

app.sh
setup.sh

Add brew-cask install code for CLIP STUDIO PAINT .  And delete security tool install comment.

:sparkles: Move self app install process

---

appstore.sh

:new: Add App Store app

---

app.sh

Uninstall RubyMine and downloader.

:sparkles: Delete web apps

---

app.sh

This hockey app is iOS app test tool.

:new: Add new app from home brew cask

---

app.sh

:new: Add new app install code

---

update.sh

update brew upgrade command
**old**
```
brew update
brew upgrade
```
**new**
```
brew upgrade --creanup
```
http://blog.n-z.jp/blog/2017-04-27-homebrew-upgrade-cleanup.html

update brew upgrade command

---

README.md
download.sh
setup.sh

- Allow user who don't have git to install it and download then

[fix] Changed the download method

---

update.sh

https://rcmdnk.com/blog/2018/03/14/computer-mac-homebrew/

:new: Add brew cask upgrade into update shell file

---

app.sh

:new: Update app install list

---

app.sh
setup.sh

:sparkles: Add gitmoji-cli install command

---

app.sh

:sparkles: Update script for app install

---

setup.sh

https://github.com/sharkdp/bat

:sparkles: Add bat command install script

---

README.md
app.sh
download.sh
settings/zsh/private.zsh
setup.sh

closes #115 #116 #117 #118 #119

:sparkles: Support Ventura

---

.github/FUNDING.yml

https://docs.github.com/ja/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

:sparkles: Create FUNDING.yml

---

README.md
settings/iTerm2/AkkeyLabProfile.json
setup.sh

:sparkles: Support Sonoma

---

app.sh
appstore.sh
setup.sh

:sparkles: Support macOS Sequoia
